//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pass_Keep.Resources.Translations.Views.Settings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pass_Keep.Resources.Translations.Views.Settings.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your login password.
        /// </summary>
        internal static string Button_Change_Login_Password {
            get {
                return ResourceManager.GetString("Button_Change_Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark theme.
        /// </summary>
        internal static string Button_Dark_Theme {
            get {
                return ResourceManager.GetString("Button_Dark_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light theme.
        /// </summary>
        internal static string Button_Light_Theme {
            get {
                return ResourceManager.GetString("Button_Light_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is auto theme enabled.
        /// </summary>
        internal static string Label_Auto_Theme_Enabled {
            get {
                return ResourceManager.GetString("Label_Auto_Theme_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danger Zone.
        /// </summary>
        internal static string Label_Danger_Zone {
            get {
                return ResourceManager.GetString("Label_Danger_Zone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ALL accounts.
        /// </summary>
        internal static string Label_Delete_All_Accounts {
            get {
                return ResourceManager.GetString("Label_Delete_All_Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is login after sleep required ?.
        /// </summary>
        internal static string Label_Is_Login_After_Sleep_Required {
            get {
                return ResourceManager.GetString("Label_Is_Login_After_Sleep_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is login required.
        /// </summary>
        internal static string Label_Login_Enabled {
            get {
                return ResourceManager.GetString("Label_Login_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Label_Login_Section {
            get {
                return ResourceManager.GetString("Label_Login_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Label_Theme_Section {
            get {
                return ResourceManager.GetString("Label_Theme_Section", resourceCulture);
            }
        }
    }
}
